image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      gp env PATH=~/.local/share/solana/install/active_release/bin:$PATH
      solana config set -u testnet
      (cd step-1 && cargo run)
      (cd step-2 && cargo run)
    command: solana-test-validator
    command: solana config get
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true

ports:
  - port: 8899
  - port: 8900
  - port: 9900
