image:
  file: .gitpod.Dockerfile
tasks:
  - before: |
      gp env PATH=~/.local/share/solana/install/active_release/bin:$PATH
      solana config set -u testnet
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true

ports:
  - port: 1024
    onOpen: ignore
  - port: 8899
    onOpen: ignore
  - port: 8900
    onOpen: ignore
  - port: 9900
    onOpen: ignore
